version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kinesis-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lgx1nv9yzo9n"
s3_prefix = "kinesis-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
